# This YAML follows the format from Backstage's guide on setting up GitHub for
# authentication
# https://backstage.io/docs/getting-started/config/authentication/#adding-a-user
#
# Make sure that the `name` field matches your actual GitHub username, and that
# the `memberOf` field matches actual organizations that have been added to the
# app-config.yaml file.
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Parkreiner
spec:
  memberOf: [coder]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: DevelopmentCats
spec:
  memberOf: [coder]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
